"use client"

import { doc, onSnapshot } from "firebase/firestore"
import { useEffect, useState } from "react"
import { callFirebase } from "@/lib/firebase/callables"
import { firestore } from "@/lib/firebase/client"
import { DEFAULT_BOOKING_SETTINGS, ORGANIZATION_ID } from "@/lib/one-stop-shop/constants"
import { AdminHeading, adminCard } from "@/components/admin/admin-shell"

type Settings = { timeZone: "Europe/Amsterdam"; durationMinutes: number; bufferMinutes: number; minimumNoticeHours: number; bookingWindowDays: number; pendingHoldHours: number; reminderHours: number; weeklySchedule: Record<string, Array<{ start: string; end: string }>>; blockedDates: string[] }
const days = [["1", "Monday"], ["2", "Tuesday"], ["3", "Wednesday"], ["4", "Thursday"], ["5", "Friday"], ["6", "Saturday"], ["7", "Sunday"]]

export default function SettingsPage() {
  const [settings, setSettings] = useState<Settings>(DEFAULT_BOOKING_SETTINGS as unknown as Settings); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false)
  useEffect(() => { if (!firestore) return; return onSnapshot(doc(firestore, `organizations/${ORGANIZATION_ID}/settings/booking`), snapshot => { if (snapshot.exists()) setSettings(snapshot.data() as Settings) }) }, [])
  const number = (key: keyof Settings, value: string) => setSettings(current => ({ ...current, [key]: Number(value) }))
  const setDay = (key: string, field: "start" | "end", value: string) => setSettings(current => ({ ...current, weeklySchedule: { ...current.weeklySchedule, [key]: [{ start: current.weeklySchedule[key]?.[0]?.start ?? "09:00", end: current.weeklySchedule[key]?.[0]?.end ?? "17:00", [field]: value }] } }))
  const toggleDay = (key: string) => setSettings(current => ({ ...current, weeklySchedule: { ...current.weeklySchedule, [key]: current.weeklySchedule[key]?.length ? [] : [{ start: "09:00", end: "17:00" }] } }))
  async function save() { setBusy(true); setMessage(""); try { await callFirebase("saveBookingSettings", settings); setMessage("Booking settings saved.") } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not save settings.") } finally { setBusy(false) } }
  return <><AdminHeading eyebrow="Configuration" title="Booking settings" description="Availability, duration, buffers, holds and blocked dates. Times use Europe/Amsterdam." action={<button onClick={() => void save()} disabled={busy} className="rounded-full bg-black px-6 py-3 text-sm text-white">{busy ? "Saving…" : "Save settings"}</button>} />{message && <p role="status" className="mb-5 rounded-xl bg-white p-4 text-sm">{message}</p>}<section className={adminCard}><h2 className="text-xl">Consultation rules</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Duration (minutes)", "durationMinutes"], ["Buffer (minutes)", "bufferMinutes"], ["Minimum notice (hours)", "minimumNoticeHours"], ["Booking window (days)", "bookingWindowDays"], ["Pending hold (hours)", "pendingHoldHours"], ["Reminder before (hours)", "reminderHours"]].map(([label, key]) => <label key={key} className="text-sm">{label}<input type="number" className="mt-2 w-full rounded-xl border px-4 py-3" value={settings[key as keyof Settings] as number} onChange={e => number(key as keyof Settings, e.target.value)} /></label>)}</div></section><section className={`${adminCard} mt-6`}><h2 className="text-xl">Weekly schedule</h2><div className="mt-5 divide-y divide-black/10">{days.map(([key, label]) => { const active = Boolean(settings.weeklySchedule[key]?.length); return <div key={key} className="grid grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-center gap-3 py-4 sm:grid-cols-[minmax(100px,1fr)_minmax(0,150px)_auto_minmax(0,150px)]"><label className="col-span-3 flex items-center gap-3 text-sm sm:col-span-1"><input type="checkbox" checked={active} onChange={() => toggleDay(key)} />{label}</label><input aria-label={`${label} start time`} type="time" disabled={!active} value={settings.weeklySchedule[key]?.[0]?.start ?? "09:00"} onChange={e => setDay(key, "start", e.target.value)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-30" /><span className="text-xs text-black/40">to</span><input aria-label={`${label} end time`} type="time" disabled={!active} value={settings.weeklySchedule[key]?.[0]?.end ?? "17:00"} onChange={e => setDay(key, "end", e.target.value)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-30" /></div> })}</div><label className="mt-6 block text-sm">Blocked dates (YYYY-MM-DD, comma-separated)<textarea className="mt-2 min-h-24 w-full rounded-xl border p-4" value={settings.blockedDates.join(", ")} onChange={e => setSettings(current => ({ ...current, blockedDates: e.target.value.split(",").map(value => value.trim()).filter(Boolean) }))} /></label></section></>
}
