"use client"

import { useMemo, useState } from "react"
import { Download, Trash2 } from "lucide-react"
import { getBytes, ref } from "firebase/storage"
import { callFirebase } from "@/lib/firebase/callables"
import { firebaseStorage } from "@/lib/firebase/client"
import { AdminHeading, adminCard } from "@/components/admin/admin-shell"
import { formatAppointment, type AdminDocument, useAdminCollection } from "@/components/admin/use-admin-collection"

export default function ClientsPage() {
  const { data: clients, loading } = useAdminCollection("clients", "createdAt")
  const { data: appointments } = useAdminCollection("appointments", "createdAt")
  const [selectedId, setSelectedId] = useState(""); const [search, setSearch] = useState(""); const [note, setNote] = useState(""); const [message, setMessage] = useState("")
  const [savingNote, setSavingNote] = useState(false)
  const selected = clients.find(client => client.id === selectedId) ?? clients[0]
  const { data: notes } = useAdminCollection(`clients/${selected?.id ?? "__none__"}/notes`, "createdAt")
  const history = useMemo(() => appointments.filter(item => item.clientId === selected?.id), [appointments, selected?.id])
  const filtered = clients.filter(client => `${client.name} ${client.email} ${client.phone}`.toLowerCase().includes(search.toLowerCase()))

  async function addNote() { if (!selected || !note.trim() || savingNote) return; setSavingNote(true); try { await callFirebase("addClientNote", { clientId: selected.id, text: note }); setNote(""); setMessage("Note saved.") } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not save note.") } finally { setSavingNote(false) } }
  async function exportData() { if (!selected) return; try { const data = await callFirebase<Record<string, string>, Record<string, unknown>>("exportClientData", { clientId: selected.id }); const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `client-${selected.id}.json`; anchor.click(); URL.revokeObjectURL(url) } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Export failed.") } }
  async function deleteData() { if (!selected || !window.confirm(`Permanently delete ${selected.name} and their CRM data? Export first if needed.`)) return; try { await callFirebase("deleteClientData", { clientId: selected.id }); setSelectedId(""); setMessage("Client data deleted.") } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Deletion failed.") } }

  return <><AdminHeading eyebrow="CRM" title="Clients" description="Contact details, appointment history, project documents and internal notes." />{message && <p role="status" className="mb-5 rounded-xl bg-white p-4 text-sm">{message}</p>}<div className="grid gap-6 xl:grid-cols-[330px_1fr]"><section className={adminCard}><input value={search} onChange={e => setSearch(e.target.value)} aria-label="Search clients" placeholder="Search clients" className="w-full rounded-xl border border-black/15 px-4 py-3 text-sm" /><div className="mt-4 divide-y divide-black/10">{filtered.map(client => <button type="button" key={client.id} onClick={() => setSelectedId(client.id)} className={`w-full px-2 py-4 text-left ${selected?.id === client.id ? "bg-black/[.03]" : ""}`}><p className="text-sm font-semibold">{client.name}</p><p className="mt-1 text-xs text-black/45">{client.email}</p></button>)}{!loading && !filtered.length && <p className="py-8 text-sm text-black/45">No clients match your search.</p>}</div></section><section className={adminCard}>{selected ? <ClientDetails client={selected} history={history} notes={notes} note={note} setNote={setNote} savingNote={savingNote} addNote={addNote} exportData={exportData} deleteData={deleteData} /> : <p className="py-12 text-center text-sm text-black/45">Select a client.</p>}</section></div></>
}

function ClientDetails({ client, history, notes, note, setNote, savingNote, addNote, exportData, deleteData }: { client: AdminDocument; history: AdminDocument[]; notes: AdminDocument[]; note: string; setNote: (value: string) => void; savingNote: boolean; addNote: () => Promise<void>; exportData: () => Promise<void>; deleteData: () => Promise<void> }) {
  async function download(file: { path: string; name: string; contentType: string }) { if (!firebaseStorage) return; const bytes = await getBytes(ref(firebaseStorage, file.path), 20 * 1024 * 1024); const url = URL.createObjectURL(new Blob([bytes], { type: file.contentType })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = file.name; anchor.click(); URL.revokeObjectURL(url) }
  return <><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-2xl">{client.name}</h2><p className="mt-2 text-sm text-black/55">{client.email} · {client.phone}</p><p className="mt-1 text-sm text-black/55">{client.location}</p></div><div className="flex gap-2"><button onClick={() => void exportData()} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-xs"><Download size={14} /> Export</button><button onClick={() => void deleteData()} className="flex items-center gap-2 rounded-xl border border-red-200 px-3 py-2 text-xs text-red-700"><Trash2 size={14} /> Delete</button></div></div><div className="mt-8"><h3 className="text-lg">Appointment history</h3><div className="mt-3 divide-y divide-black/10">{history.map(item => <div key={item.id} className="py-4"><div className="flex justify-between gap-3"><p className="text-sm">{item.service}</p><span className="text-xs capitalize text-black/50">{item.status}</span></div><p className="mt-1 text-xs text-black/45">{formatAppointment(item.startsAt)} · {item.mode}</p>{item.files?.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{item.files.map((file: { path: string; name: string; contentType: string }) => <button key={file.path} onClick={() => void download(file)} className="rounded-lg border px-3 py-2 text-xs">Download {file.name}</button>)}</div>}</div>)}</div></div><div className="mt-8"><h3 className="text-lg">Internal notes</h3><div className="mt-3 space-y-2">{notes.map(item => <div key={item.id} className="rounded-xl bg-black/[.03] p-4"><p className="text-sm leading-6">{item.text}</p><p className="mt-2 text-xs text-black/40">{formatAppointment(item.createdAt)}</p></div>)}{!notes.length && <p className="text-sm text-black/40">No notes yet.</p>}</div><textarea value={note} onChange={e => setNote(e.target.value)} className="mt-4 min-h-28 w-full rounded-xl border border-black/15 p-4 text-sm" aria-label="Internal note" placeholder="Visible only to authorised team members" /><button disabled={savingNote || !note.trim()} onClick={() => void addNote()} className="mt-3 rounded-full bg-black px-5 py-2.5 text-sm text-white">{savingNote ? "Saving…" : "Save note"}</button></div></>
}
