"use client"

import { useState } from "react"
import { callFirebase } from "@/lib/firebase/callables"
import { AdminHeading, adminCard } from "@/components/admin/admin-shell"
import { formatAppointment, useAdminCollection } from "@/components/admin/use-admin-collection"

export default function TeamPage() {
  const { data: members } = useAdminCollection("members", "createdAt"); const [email, setEmail] = useState(""); const [displayName, setDisplayName] = useState(""); const [role, setRole] = useState<"admin" | "staff">("staff"); const [message, setMessage] = useState("")
  async function invite(event: React.FormEvent) { event.preventDefault(); setMessage(""); try { await callFirebase("inviteMember", { email, displayName, role }); setEmail(""); setDisplayName(""); setMessage("Invitation queued. The member receives a secure password setup link.") } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not invite member.") } }
  async function update(uid: string, memberRole: "admin" | "staff", disabled: boolean) { try { await callFirebase("updateMember", { uid, role: memberRole, disabled }); setMessage("Team member updated. They must refresh their session to receive new claims.") } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not update member.") } }
  return <><AdminHeading eyebrow="Access control" title="Team" description="Invite admins or staff. Staff cannot access team or sensitive booking settings." />{message && <p role="status" className="mb-5 rounded-xl bg-white p-4 text-sm">{message}</p>}<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><section className={adminCard}><h2 className="text-xl">Members</h2><div className="mt-5 divide-y divide-black/10">{members.map(member => <div key={member.id} className="flex flex-col justify-between gap-4 py-4 2xl:flex-row 2xl:items-center"><div><p className="text-sm font-semibold">{member.displayName}</p><p className="text-xs text-black/45">{member.email} · added {formatAppointment(member.createdAt)}</p></div><div className="flex gap-2"><select aria-label={`Role for ${member.displayName}`} value={member.role} onChange={e => void update(member.id, e.target.value as "admin" | "staff", member.status === "disabled")} className="rounded-lg border px-3 py-2 text-xs"><option value="staff">staff</option><option value="admin">admin</option></select><button onClick={() => void update(member.id, member.role, member.status !== "disabled")} className="rounded-lg border px-3 py-2 text-xs">{member.status === "disabled" ? "Enable" : "Disable"}</button></div></div>)}</div></section><form onSubmit={invite} className={adminCard}><h2 className="text-xl">Invite member</h2><label className="mt-5 block text-sm">Name<input required value={displayName} onChange={e => setDisplayName(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3" /></label><label className="mt-4 block text-sm">Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3" /></label><label className="mt-4 block text-sm">Role<select value={role} onChange={e => setRole(e.target.value as "admin" | "staff")} className="mt-2 w-full rounded-xl border px-4 py-3"><option value="staff">Staff</option><option value="admin">Admin</option></select></label><button className="mt-6 w-full rounded-full bg-black px-5 py-3 text-sm text-white">Send invitation</button></form></div></>
}
